var users = [
  { "_id" : "GleyfryiptabAyHou", "createdAt" : ISODate("2019-02-11T12:37:49.490Z"), "services" : { "password" : { "bcrypt" : "$2b$10$MtJgYCtnJRXG9G9CHNveJux4hQk4I6N1C69MJpUsePMcOfNyAf/2." } }, "username" : "uGleyfryiptabAyHou", "emails" : [ { "address" : "uGleyfryiptabAyHou@user.tld", "verified" : true } ], "type" : "user", "status" : "offline", "active" : true, "name" : "uGleyfryiptabAyHou", "_updatedAt" : ISODate("2019-02-11T12:37:49.490Z"), "roles" : [ "admin" ], "settings" : {  } },
  { "_id" : "FitIcJaynreyncecI", "createdAt" : ISODate("2019-02-11T12:37:49.490Z"), "services" : { "password" : { "bcrypt" : "$2b$10$MtJgYCtnJRXG9G9CHNveJux4hQk4I6N1C69MJpUsePMcOfNyAf/2." } }, "username" : "uFitIcJaynreyncecI", "emails" : [ { "address" : "uFitIcJaynreyncecI@user.tld", "verified" : true } ], "type" : "user", "status" : "offline", "active" : true, "name" : "uFitIcJaynreyncecI", "_updatedAt" : ISODate("2019-02-11T12:37:49.490Z"), "roles" : [ "admin" ], "settings" : {  } },
  { "_id" : "ossAxlibWonnundyi", "createdAt" : ISODate("2019-02-11T12:37:49.490Z"), "services" : { "password" : { "bcrypt" : "$2b$10$MtJgYCtnJRXG9G9CHNveJux4hQk4I6N1C69MJpUsePMcOfNyAf/2." } }, "username" : "uossAxlibWonnundyi", "emails" : [ { "address" : "uossAxlibWonnundyi@user.tld", "verified" : true } ], "type" : "user", "status" : "offline", "active" : true, "name" : "uossAxlibWonnundyi", "_updatedAt" : ISODate("2019-02-11T12:37:49.490Z"), "roles" : [ "admin" ], "settings" : {  } },
  { "_id" : "orcevouQuabtifyey", "createdAt" : ISODate("2019-02-11T12:37:49.490Z"), "services" : { "password" : { "bcrypt" : "$2b$10$MtJgYCtnJRXG9G9CHNveJux4hQk4I6N1C69MJpUsePMcOfNyAf/2." } }, "username" : "uorcevouQuabtifyey", "emails" : [ { "address" : "uorcevouQuabtifyey@user.tld", "verified" : true } ], "type" : "user", "status" : "offline", "active" : true, "name" : "uorcevouQuabtifyey", "_updatedAt" : ISODate("2019-02-11T12:37:49.490Z"), "roles" : [ "admin" ], "settings" : {  } },
  { "_id" : "torAjquaileofgejA", "createdAt" : ISODate("2019-02-11T12:37:49.490Z"), "services" : { "password" : { "bcrypt" : "$2b$10$MtJgYCtnJRXG9G9CHNveJux4hQk4I6N1C69MJpUsePMcOfNyAf/2." } }, "username" : "utorAjquaileofgejA", "emails" : [ { "address" : "utorAjquaileofgejA@user.tld", "verified" : true } ], "type" : "user", "status" : "offline", "active" : true, "name" : "utorAjquaileofgejA", "_updatedAt" : ISODate("2019-02-11T12:37:49.490Z"), "roles" : [ "admin" ], "settings" : {  } },
  { "_id" : "elgofekichGhosyac", "createdAt" : ISODate("2019-02-11T12:37:49.490Z"), "services" : { "password" : { "bcrypt" : "$2b$10$MtJgYCtnJRXG9G9CHNveJux4hQk4I6N1C69MJpUsePMcOfNyAf/2." } }, "username" : "uelgofekichGhosyac", "emails" : [ { "address" : "uelgofekichGhosyac@user.tld", "verified" : true } ], "type" : "user", "status" : "offline", "active" : true, "name" : "uelgofekichGhosyac", "_updatedAt" : ISODate("2019-02-11T12:37:49.490Z"), "roles" : [ "admin" ], "settings" : {  } },
  { "_id" : "wanHeipocceskenEr", "createdAt" : ISODate("2019-02-11T12:37:49.490Z"), "services" : { "password" : { "bcrypt" : "$2b$10$MtJgYCtnJRXG9G9CHNveJux4hQk4I6N1C69MJpUsePMcOfNyAf/2." } }, "username" : "uwanHeipocceskenEr", "emails" : [ { "address" : "uwanHeipocceskenEr@user.tld", "verified" : true } ], "type" : "user", "status" : "offline", "active" : true, "name" : "uwanHeipocceskenEr", "_updatedAt" : ISODate("2019-02-11T12:37:49.490Z"), "roles" : [ "admin" ], "settings" : {  } },
  { "_id" : "UnfuckMulAurgyofa", "createdAt" : ISODate("2019-02-11T12:37:49.490Z"), "services" : { "password" : { "bcrypt" : "$2b$10$MtJgYCtnJRXG9G9CHNveJux4hQk4I6N1C69MJpUsePMcOfNyAf/2." } }, "username" : "uUnfuckMulAurgyofa", "emails" : [ { "address" : "uUnfuckMulAurgyofa@user.tld", "verified" : true } ], "type" : "user", "status" : "offline", "active" : true, "name" : "uUnfuckMulAurgyofa", "_updatedAt" : ISODate("2019-02-11T12:37:49.490Z"), "roles" : [ "admin" ], "settings" : {  } },
  { "_id" : "BitandankugNidhyt", "createdAt" : ISODate("2019-02-11T12:37:49.490Z"), "services" : { "password" : { "bcrypt" : "$2b$10$MtJgYCtnJRXG9G9CHNveJux4hQk4I6N1C69MJpUsePMcOfNyAf/2." } }, "username" : "uBitandankugNidhyt", "emails" : [ { "address" : "uBitandankugNidhyt@user.tld", "verified" : true } ], "type" : "user", "status" : "offline", "active" : true, "name" : "uBitandankugNidhyt", "_updatedAt" : ISODate("2019-02-11T12:37:49.490Z"), "roles" : [ "admin" ], "settings" : {  } },
  { "_id" : "quoshIpIDiejinqui", "createdAt" : ISODate("2019-02-11T12:37:49.490Z"), "services" : { "password" : { "bcrypt" : "$2b$10$MtJgYCtnJRXG9G9CHNveJux4hQk4I6N1C69MJpUsePMcOfNyAf/2." } }, "username" : "uquoshIpIDiejinqui", "emails" : [ { "address" : "uquoshIpIDiejinqui@user.tld", "verified" : true } ], "type" : "user", "status" : "offline", "active" : true, "name" : "uquoshIpIDiejinqui", "_updatedAt" : ISODate("2019-02-11T12:37:49.490Z"), "roles" : [ "admin" ], "settings" : {  } }
]

db.rocketchat_room.remove({"_id" : {$ne: "GENERAL"}})
db.rocketchat_message.remove({})
db.rocketchat_subscription.remove({})

db.users.insert(users)
